### ISSUE TITLE
Change Applicant Routes to Identifiers

### ISSUE THREAD

**Issue by grandynguyen** [keith/asc_476#2]
I will be working on this.

**Comment by grandynguyen** [comment]
TODO: Can't edit gpa

**Comment by keith** [comment]
We don't have the identifiers in the DB yet I don't think. We need to add those on `before_create` so they never change

**Comment by keith** [comment]
I lied https://github.com/Keithbsmiley/asc_476/blob/master/app/models/applicant.rb#L8

**Comment by grandynguyen** [comment]
The new urls are in place. I need to write some tests though.
